// Exact exported assets from New Here V2 in Figma.
export const entryAssets = {
  login: {
    imgMargin: require('../../assets/entry/login-c5d1b.svg'),
    imgMargin1: require('../../assets/entry/login-6407b.svg'),
    imgContainer: require('../../assets/entry/login-bca05.svg'),
    imgContainer1: require('../../assets/entry/login-28520.svg'),
    imgSvg: require('../../assets/entry/login-b5051.svg'),
    imgSvg1: require('../../assets/entry/login-75a12.svg'),
  },
  welcome: {
    imgBeautifulSunDrenchedCobblestoneAlleyVisual: require('../../assets/entry/welcome-48d45.png'),
    imgVector: require('../../assets/entry/welcome-b21fd.svg'),
    imgVector1: require('../../assets/entry/welcome-472e8.svg'),
    imgVector2: require('../../assets/entry/welcome-9f598.svg'),
    imgVector3: require('../../assets/entry/welcome-4a06e.svg'),
    imgVector4: require('../../assets/entry/welcome-918eb.svg'),
    imgVector5: require('../../assets/entry/welcome-b5d33.svg'),
    imgVector6: require('../../assets/entry/welcome-f0eed.svg'),
    imgContainer: require('../../assets/entry/welcome-3a883.svg'),
  },
  intro: {
    imgPhoto1516483638261F4Dbaf036963: require('../../assets/entry/intro-b0ab2.png'),
    imgSvgLivingMistVectorContours: require('../../assets/entry/intro-753e9.svg'),
    imgContainer: require('../../assets/entry/intro-49493.svg'),
    imgContainer1: require('../../assets/entry/intro-db0d3.svg'),
    imgContainer2: require('../../assets/entry/intro-4d349.svg'),
    imgContainer3: require('../../assets/entry/intro-03d99.svg'),
  },
  recovery: {
    imgImage: require('../../assets/entry/recovery-3390e.png'),
    imgContainer: require('../../assets/entry/recovery-a5716.svg'),
    imgIcon: require('../../assets/entry/recovery-dbfbb.svg'),
    imgContainer1: require('../../assets/entry/recovery-9a661.svg'),
    imgContainer2: require('../../assets/entry/recovery-98ea9.svg'),
  },
  signup: {
    imgContainer: require('../../assets/entry/signup-d25b5.svg'),
    imgSvg: require('../../assets/entry/signup-6abaa.svg'),
    imgContainer1: require('../../assets/entry/signup-55465.svg'),
    imgButton: require('../../assets/entry/signup-fd202.svg'),
    imgContainer2: require('../../assets/entry/signup-a45f7.svg'),
  },
  location: {
    imgContainer: require('../../assets/entry/location-650e7.svg'),
    imgMargin: require('../../assets/entry/location-6d720.svg'),
    imgContainer1: require('../../assets/entry/location-25650.svg'),
    imgContainer2: require('../../assets/entry/location-1449a.svg'),
    imgContainer3: require('../../assets/entry/location-d9f7b.svg'),
    imgContainer4: require('../../assets/entry/location-75ce9.svg'),
  },
  details: {
    imgContainer: require('../../assets/entry/details-ad160.svg'),
    imgMargin: require('../../assets/entry/details-33438.svg'),
    imgMargin1: require('../../assets/entry/details-04089.svg'),
    imgContainer1: require('../../assets/entry/details-b0783.svg'),
  },
  interests: {
    imgContainer: require('../../assets/entry/interests-650e7.svg'),
    imgContainer1: require('../../assets/entry/interests-59bc0.svg'),
    imgContainer2: require('../../assets/entry/interests-19ae3.svg'),
    imgContainer3: require('../../assets/entry/interests-da381.svg'),
    imgContainer4: require('../../assets/entry/interests-c7a53.svg'),
    imgContainer5: require('../../assets/entry/interests-ac358.svg'),
    imgContainer6: require('../../assets/entry/interests-086cb.svg'),
    imgContainer7: require('../../assets/entry/interests-617dc.svg'),
    imgContainer8: require('../../assets/entry/interests-458df.svg'),
    imgContainer9: require('../../assets/entry/interests-9a661.svg'),
    imgContainer10: require('../../assets/entry/interests-914ca.svg'),
  },
  completion: {
    imgBaseMapUnderlayGoogleStaticMapTarget: require('../../assets/entry/completion-67eb5.png'),
    imgSvg: require('../../assets/entry/completion-3c92b.svg'),
    imgContainer: require('../../assets/entry/completion-78ea1.svg'),
    imgContainer1: require('../../assets/entry/completion-d3302.svg'),
    imgContainer2: require('../../assets/entry/completion-5bb26.svg'),
  },
} as const;

